# Generated by Django 5.0 on 2025-10-14 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('A', 'Admin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courses_completed', models.IntegerField(default=0)),
                ('courses_in_progress', models.IntegerField(default=0)),
            ],
        ),
    ]
