# Generated by Django 6.0 on 2025-12-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
