# Generated by Django 6.0 on 2025-12-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
