# Generated by Django 6.0 on 2025-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_image_url_course_image_base64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='explnation',
            new_name='explanation',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
