# Generated by Django 6.0 on 2025-12-20 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_explnation_multiplechoicequestion_explanation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'task')},
        ),
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
    ]
